# Generated by Django 5.2.17 on 2026-08-07 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "academia",
                "verbose_name_plural": "academias",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Número da máquina na academia"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "device_token",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="core.academia",
                    ),
                ),
            ],
            options={
                "verbose_name": "máquina",
                "verbose_name_plural": "máquinas",
                "unique_together": {("academia", "number")},
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "hevy_exercise_template_id",
                    models.CharField(
                        help_text="ID do exercise template na API do Hevy (ex: 1E9A6B8E)",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "exercício",
                "verbose_name_plural": "exercícios",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID que o aluno digita no tablet", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("pin_hash", models.CharField(editable=False, max_length=128)),
                (
                    "hevy_api_key_encrypted",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("hevy_linked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.academia",
                    ),
                ),
            ],
            options={
                "verbose_name": "aluno",
                "verbose_name_plural": "alunos",
                "unique_together": {("academia", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="StudentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.machine",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("sets", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("pushed", "Enviado ao Hevy"),
                            ("failed", "Falha no envio"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "hevy_workout_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("error_detail", models.TextField(blank=True, default="")),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_logs",
                        to="core.exercise",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="core.machine",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de treino",
                "verbose_name_plural": "registros de treino",
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login falhou"),
                            ("hevy_linked", "Conta Hevy vinculada"),
                            ("workout_logged", "Treino registrado"),
                            ("hevy_pushed", "Enviado ao Hevy"),
                            ("hevy_push_failed", "Falha no envio ao Hevy"),
                            ("session_expired", "Sessão expirada"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.academia",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.machine",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de uso",
                "verbose_name_plural": "eventos de uso",
                "indexes": [
                    models.Index(
                        fields=["academia", "event_type", "created_at"],
                        name="core_usagee_academi_4edd3c_idx",
                    )
                ],
            },
        ),
    ]
