# Generated by Django 5.2.17 on 2026-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("pushing", "Enviando"),
                    ("pushed", "Enviado ao Hevy"),
                    ("failed", "Falha no envio"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
