# Generated by Django 5.2.17 on 2026-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_workoutlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="academia",
            name="admin_pin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de manutenção para sair do modo quiosque no tablet. Vazio desativa a saída.",
                max_length=12,
            ),
        ),
    ]
