# Generated by Django 5.2.17 on 2026-08-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_academia_admin_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login falhou"),
                    ("hevy_linked", "Conta Hevy vinculada"),
                    ("workout_logged", "Treino registrado"),
                    ("hevy_pushed", "Enviado ao Hevy"),
                    ("hevy_push_failed", "Falha no envio ao Hevy"),
                    ("session_expired", "Sessão expirada"),
                    ("tablet_paired", "Tablet pareado"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PairingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_codes",
                        to="core.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "código de pareamento",
                "verbose_name_plural": "códigos de pareamento",
                "ordering": ["-created_at"],
            },
        ),
    ]
