# Generated by Django 5.2.17 on 2026-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_usageevent_event_type_pairingcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
